### ISSUE TITLE
Adding support for charmm-gui through CONNECT records 

### ISSUE THREAD

**Issue by Vikasdubey0551** [tlemmin/glycosylator#2]
Hi, 

I really like this package and this is a suggestion for a feature. It would be nice to add `CONNECT` records in the output PDB  files for the glycans. It would make the structure compatible with the [charmm-GUI](http://www.charmm-gui.org/). In the presence of `CONNECT` records,  charmm-gui can autodetect the glycans, then one can continue the modeling of the system and generating the parameters for all the simulation softwares. In the absence of `CONNECT` records, charmm-gui treats glycans as `HETATM`, which are not connected to protein.

**Comment by tlemmin** [comment]
Thanks for your suggestion. It has been on my to-do list. I'll try to add it soon.
I have already added the possibility to use psfgen for generating the topology of the glycoprotein.

**Comment by Vikasdubey0551** [comment]
Great to hear that. I discovered a workaround for getting the `CONECT` records using pymol and chimera. I am writing this for someone, who stumbled across this thread while the development process.
### Pymol
1. load glycan pdb to pymol
2. in pymol command line, write the following :
    > set pdb_retain_ids, on
    > set pdb_conect_all, off
    > save yourfile.pdb
3. This will write `CONECT` records in the end for only `HETATMs`.

### Chimera 
 

1. Upload glycan pdb to chimera by **clicking -> file -> open**.
2.  Go to **Select -> Chain -> choose chain containing glycans yourself**.
3. Go to **Tools-> Structure Editing -> Renumber Residues**.
4. Click on selected residues and renumber the glycan residues by typing a desired number.
5. Go to **File-> Save PDB -> save the pdb**.
6. This will write `CONECT` records in the end for only `HETATMs`.
