### ISSUE TITLE
D03 error

### ISSUE THREAD

**Issue by saralydon** [tlemmin/glycosylator#4]
There seems to be an error when attempting to run the D03 demo_gycosylator file. There is an AttributeError reported that says 'NoneType' object has no attribute 'getResnames', starting on line 69 of the file where glycosylate is called. Do you have any recommendations on how to address this?

**Comment by tlemmin** [comment]
I think I fixed the problem. Please let me know if it works for you.

**Comment by saralydon** [comment]
Thank you, this did fix the problem! I appreciate your reply. My research mentor and I hope to use Glycosylator in some of our antibody research, and we had a question regarding the numerical energies returned by the “compute_total_energy" method. In your opinion, which energy measurement would be more relevant to use for comparison when ranking the stability of different glycan conformations, ’self_non_bonded_energy’ or ‘environment_energy’? Thank you!

**Comment by tlemmin** [comment]
I would say that it is probably best to use an external program to estimate the energy of different conformations (e.g. a MD engine such as NAMD). The energy function implemented in glycosylator are only very crude approximation used to remove clashes. 
Please feel free to contact me by email, if you want to further discuss this. :)
