### ISSUE TITLE
Error in background function

### ISSUE THREAD

**Issue by newjhon2013** [tlemmin/glycosylator#5]
Hi, 
I have successfully installed and opened the GUI. An error appeared as NoneType object has no attribute getSegnames. Can you give me some advice for fixing this problem ? 

Thanks 
![574302690](https://user-images.githubusercontent.com/55539199/146375618-cd33b471-5fe9-4450-8c05-a5bf06673c1b.jpg)

**Comment by tlemmin** [comment]
It seems like there is an issue with loading the glycoprotein. Could you try loading one of the demo files (e.g. 4tvp.pdb)

**Comment by awenborn** [comment]
I'm running into the same problem.

I created new conda environment using the `environment.yml` file and used

```
conda activate glycosylator
conda update decorator
```

to downgrade to a compatible version of decorator (v4.4.2)... not sure if this was the best way to create a compatible 2.7 env, but get same results as @newjhon2013 when trying to use glycosylator_GUI. It launches fine but produces the same error when trying to load any of the demo files.. did you find any cause/solution for this?

Many thanks, Adam

**Comment by tlemmin** [comment]
Which OS are you using?
Are you getting this error with one of the demo files or your own glycoprotein?

**Comment by awenborn** [comment]
Thanks for the quick reply and thanks for developing/maintaining this project... it looks like it could be really useful for our research.

I'm using it on a Linux workstation that's running CentOS v7.9.2009

I had a delve into it this afternoon and _certain_ files will open and process without errors (e.g. the 4tvp.pdb file in the `/support/examples` directory) but others (including those in the demo directories) will throw similar errors when trying to open the file, when trying to select specific protein chains, or when trying to run "Remove Clashes"... the point of error seems to vary a lot between file-to-file.

I delved a little deeper trying to load my _own_ PDBs and (having resolved various issues that seemingly pertained to hydrogen occupancy) the general conclusion was that if they contained prexisting glycans then it would throw an error when trying to view those chains to which the glycans were attached, but if they contained **_no_** prexisting glycans then it would throw an error on trying to process "Remove Clashes".

I don't know if that helps at all?!

Would be happy to post the errors that are throw if that doesn't ring any bells.

Many thanks again, Adam

**Comment by tlemmin** [comment]
Could you tell me which demos PDBs don't work?

The graphical interface seems to be causing a lot of problems. Feel free to email me, if you have a specific problem that you want to solve. I might be able to help with a work around.
